# Generated by Django 3.2 on 2022-11-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Email для рассылок', 'verbose_name_plural': 'Email для рассылок'},
        ),
    ]
